!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 64
  - - buffer_size
    - 100000
  - - ent_coef
    - auto
  - - env_wrapper
    - - gymnasium.wrappers.time_limit.TimeLimit:
          max_episode_steps: 480
      - rl_zoo3.wrappers.HistoryWrapper:
          horizon: 48
  - - gamma
    - 0.99
  - - gradient_steps
    - 64
  - - learning_rate
    - 0.0017
  - - learning_starts
    - 1000
  - - n_timesteps
    - 1000000.0
  - - normalize
    - true
  - - policy
    - MlpPolicy
  - - policy_kwargs
    - dict(log_std_init=-2, net_arch=[64, 64])
  - - sde_sample_freq
    - 64
  - - tau
    - 0.01
  - - train_freq
    - 128
  - - use_sde
    - true
  - - use_sde_at_warmup
    - true
