!!python/object/apply:collections.OrderedDict
- - - ent_coef
    - 9.6e-05
  - - env_wrapper
    - - gymnasium.wrappers.time_limit.TimeLimit:
          max_episode_steps: 480
      - rl_zoo3.wrappers.HistoryWrapper:
          horizon: 48
  - - gae_lambda
    - 0.9
  - - gamma
    - 0.95
  - - learning_rate
    - 3.2e-05
  - - max_grad_norm
    - 0.5
  - - n_steps
    - 8
  - - n_timesteps
    - 1000000.0
  - - normalize
    - true
  - - normalize_advantage
    - false
  - - policy
    - MlpPolicy
  - - policy_kwargs
    - dict(log_std_init=-2, ortho_init=False)
  - - use_rms_prop
    - true
  - - use_sde
    - true
  - - vf_coef
    - 0.4
