
# ==== Custom Envs ===
energy_net-v0:
  env_wrapper:
    - gymnasium.wrappers.time_limit.TimeLimit:
        max_episode_steps: 480
    - rl_zoo3.wrappers.HistoryWrapper:
        horizon: 5
  n_timesteps: !!float 1e6
  policy: 'MlpPolicy'
  learning_rate: !!float 7.3e-4
  batch_size: 256
  ent_coef: 0.0001
  gamma: 0.99
  normalize: true
  # train_freq: 64
  # train_freq: [1, "episode"]
  # gradient_steps: -1
  # gradient_steps: 64
  # learning_starts: 48
  # use_sde_at_warmup: True
  use_sde: True
  sde_sample_freq: 64
  policy_kwargs: "dict(log_std_init=-2, net_arch=[64, 64])"

